# Generated by Django 3.2.4 on 2021-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRentalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromcategory', models.CharField(choices=[('earthmoving', 'Earth Moving'), ('aerial access', 'Aerial Access'), ('compaction', 'Compaction'), ('light towers', 'Light Towers')], default='Earth Moving', max_length=255)),
                ('tocategory', models.CharField(choices=[('earthmoving', 'Earth Moving'), ('aerial access', 'Aerial Access'), ('compaction', 'Compaction'), ('light towers', 'Light Towers')], default='Earth Moving', max_length=255)),
                ('make', models.CharField(max_length=200)),
                ('datereceived', models.DateField()),
                ('datereturned', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BuyoutCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyrent', models.CharField(choices=[('b', 'Buy'), ('r', 'Rent')], default='Buy', max_length=4)),
                ('jobnum', models.CharField(max_length=200)),
                ('vendornum', models.CharField(max_length=200)),
                ('returned', models.CharField(choices=[('y', 'Y'), ('n', 'N')], max_length=1)),
                ('buyoutprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuyoutForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobnum', models.CharField(max_length=200)),
                ('vendornum', models.CharField(max_length=200)),
                ('rentalassetid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('earthmoving', 'Earth Moving'), ('aerial access', 'Aerial Access'), ('compaction', 'Compaction'), ('light towers', 'Light Towers')], default='Earth Moving', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serialnum', models.CharField(max_length=200)),
                ('vendornum', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('earthmoving', 'Earth Moving'), ('aerial access', 'Aerial Access'), ('compaction', 'Compaction'), ('light towers', 'Light Towers')], default='Earth Moving', max_length=255)),
                ('buyrent', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='Buy', max_length=4)),
                ('returned', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicenum', models.CharField(max_length=200)),
                ('ordernum', models.CharField(max_length=200)),
                ('orderdetails', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobnum', models.CharField(max_length=200)),
                ('ordernum', models.CharField(max_length=200)),
                ('assetid', models.CharField(max_length=200)),
                ('jobdetails', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=200)),
                ('jobnums', models.CharField(max_length=200)),
                ('vendornum', models.CharField(max_length=200)),
                ('assetnum', models.CharField(max_length=200)),
                ('dateplaced', models.DateField()),
                ('dateneeded', models.DateField()),
                ('dateentered', models.DateField()),
                ('expecteddur', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReturnSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=200)),
                ('invoicenum', models.CharField(max_length=200)),
                ('returndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendornum', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phonenum', models.CharField(max_length=200)),
                ('salesman', models.CharField(max_length=200)),
                ('ponum', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyrent', models.CharField(choices=[('b', 'Buy'), ('r', 'Rent')], default='Buy', max_length=4)),
                ('jobnum', models.CharField(max_length=200)),
                ('activejob', models.CharField(choices=[('y', 'Y'), ('n', 'N')], max_length=1)),
                ('vendornum', models.CharField(max_length=200)),
                ('returned', models.CharField(choices=[('y', 'Y'), ('n', 'N')], max_length=1)),
                ('datereceived', models.DateField()),
                ('datereturned', models.DateField()),
                ('rentaldatefrom', models.DateField()),
                ('rentaldateto', models.DateField()),
            ],
        ),
    ]
