# Generated by Django 3.2.4 on 2021-06-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermaster',
            old_name='assetnum',
            new_name='assetid',
        ),
    ]
