# Generated by Django 3.2.4 on 2021-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('earthmoving', 'Earth Moving'), ('aerial access', 'Aerial Access'), ('compaction', 'Compaction'), ('light towers', 'Light Towers')], default='Earth Moving', max_length=255),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('earthmoving', 'Earth Moving'), ('aerial access', 'Aerial Access'), ('compaction', 'Compaction'), ('light towers', 'Light Towers')], default='Earth Moving', max_length=255),
        ),
    ]
