# Generated by Django 3.2.4 on 2021-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsite', '0002_auto_20210625_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRentalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromcategory', models.CharField(choices=[('earthmoving', 'Earth Moving'), ('aerial access', 'Aerial Access'), ('compaction', 'Compaction'), ('light towers', 'Light Towers')], default='Earth Moving', max_length=255)),
                ('tocategory', models.CharField(choices=[('earthmoving', 'Earth Moving'), ('aerial access', 'Aerial Access'), ('compaction', 'Compaction'), ('light towers', 'Light Towers')], default='Earth Moving', max_length=255)),
                ('make', models.CharField(max_length=200)),
                ('datereceived', models.DateField()),
                ('datereturned', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BuyoutCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyrent', models.CharField(choices=[('b', 'Buy'), ('r', 'Rent')], default='Buy', max_length=4)),
                ('jobnum', models.CharField(max_length=200)),
                ('vendornum', models.CharField(max_length=200)),
                ('returned', models.CharField(choices=[('y', 'Y'), ('n', 'N')], max_length=1)),
                ('buyoutprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuyoutForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobnum', models.CharField(max_length=200)),
                ('vendornum', models.CharField(max_length=200)),
                ('rentalassetid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyrent', models.CharField(choices=[('b', 'Buy'), ('r', 'Rent')], default='Buy', max_length=4)),
                ('jobnum', models.CharField(max_length=200)),
                ('activejob', models.CharField(choices=[('y', 'Y'), ('n', 'N')], max_length=1)),
                ('vendornum', models.CharField(max_length=200)),
                ('returned', models.CharField(choices=[('y', 'Y'), ('n', 'N')], max_length=1)),
                ('datereceived', models.DateField()),
                ('datereturned', models.DateField()),
                ('rentaldatefrom', models.DateField()),
                ('rentaldateto', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='buyrent',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='Buy', max_length=4),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='returned',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'N')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='dateentered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='dateneeded',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='dateplaced',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='expecteddur',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='returnslip',
            name='returndate',
            field=models.DateField(),
        ),
    ]
