# Generated by Django 3.2.4 on 2021-06-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsite', '0002_rename_assetnum_ordermaster_assetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='expecteddur',
            field=models.CharField(max_length=200),
        ),
    ]
