# Generated by Django 3.2.4 on 2021-06-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsite', '0002_auto_20210625_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serialnum', models.CharField(max_length=200)),
                ('vendornum', models.CharField(max_length=200)),
                ('buyrent', models.CharField(choices=[('b', 'Buy'), ('r', 'Rent')], default='Buy', max_length=4)),
                ('returned', models.CharField(choices=[('y', 'Y'), ('n', 'N')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalsite.page')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicenum', models.CharField(max_length=200)),
                ('ordernum', models.CharField(max_length=200)),
                ('orderdetails', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobnum', models.CharField(max_length=200)),
                ('ordernum', models.CharField(max_length=200)),
                ('assetid', models.CharField(max_length=200)),
                ('jobdetails', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=200)),
                ('jobnums', models.CharField(max_length=200)),
                ('vendornum', models.CharField(max_length=200)),
                ('assetnum', models.CharField(max_length=200)),
                ('dateplaced', models.CharField(max_length=200)),
                ('dateneeded', models.CharField(max_length=200)),
                ('dateentered', models.CharField(max_length=200)),
                ('expecteddur', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=200)),
                ('invoicenum', models.CharField(max_length=200)),
                ('returndate', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
