# Generated by Django 3.2.4 on 2021-06-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsite', '0003_alter_ordermaster_expecteddur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='activejob',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='buyrent',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='Buy', max_length=4),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='returned',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
