# Generated by Django 3.2.4 on 2021-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsite', '0003_auto_20210628_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='returned',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3),
        ),
    ]
